project:
  type: book
  output-dir: docs

book:
  title: "Bootcamp Desarrollo Web FullStack"
  author: "Diego Saavedra"
  output-file: "bootcamp_desarrollo_web_fullstack"  
  date: today
  date-format: medium
  favicon: logo.jpeg
  description: Bootcamp de Desarrollo Web FullStack con Python, Django y React
  keyword: Python, Django, React, FullStack, Bootcamp
  url: https://github.com/statick88/bootcamp_desarrollo_web_fullstack
  page-navigation: true
  sidebar: 
    logo: logo.jpeg
    search: true
    collapse-level: 1

  repo-subdir: book
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  image: logo.jpeg

  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
        
  chapters:

    - part: "Unidad 0: Introducción a Git y GitHub"
      chapters:
      - index.qmd
      - unidades/unidad0/1_git_y_github.qmd
      - unidades/unidad0/2_github_classroom.qmd

    - part: "Unidad 1: Introducción e Instalaciones Necesarias"
      chapters:
      - unidades/unidad1/1_introduccion.qmd
      - unidades/unidad1/2_introduccion_a_la_programacion.qmd
      - unidades/unidad1/3_tipos_de_datos.qmd
      - unidades/unidad1/4_control_de_flujo.qmd
      - unidades/unidad1/5_funciones_y_recursividad.qmd

    - part: "Unidad 2: Programación Orientada a Objetos"
      chapters: 
        - unidades/unidad2/1_programacion_orientada_a_objetos.qmd

    - part: "Unidad 3: Módulos y Paquetes"
      chapters: 
        - unidades/unidad3/1_modulos_python.qmd

    - part: "Unidad 4: Docker"
      chapters: 
        - unidades/unidad4/1_docker.qmd
        - unidades/unidad4/2_docker_compose.qmd
        - unidades/unidad4/3_DevContainers.qmd

    - part: "Proyectos"
      chapters: 
        - unidades/Proyectos/3_funciones.qmd
        - unidades/Proyectos/1_proyecto_modulos.qmd
        - unidades/Proyectos/2_proyecto_poo.qmd
        - unidades/Proyectos/4_proyecto_poo_2.qmd

bibliography: references.bib
biblio-style: "apalike"

format:
  html:
    number-sections: false
    theme: 
      dark:  solar #slate, darkly, solar, superhero, vapor
      # light: cosmo
    number-depth: 4
    link-external-icon: true
    link-external-newwindow: true
    css: css/styles.css

  pdf:
    documentclass: scrreprt
    classoption: ["onepage", "openany"]
    papersize: a4
    toc: true
    margin-top: 35mm
    margin-left: 30mm
    margin-bottom: 30mm
    margin-right: 30mm
    titlepage-geometry: 
      - top=35mm
      - bottom=30mm
      - right=30mm
      - left=30mm
  epub: 
    belongs-to-collection: "Bootcamp Desarrollo Web FullStack"
    group-position: 0
    creator: "Lcdo. Diego Saavedra Mgtr."
    rights: "© Statick | 2024"
    fig-responsive: true
    number-sections: true

filters:
  - naquiz
